class Area < ActiveHash::Base
  self.data = [
    { :id => 1, :state =>	"CA", :county =>	"San Diego County", :city => "Alpine", :neighborhood => "", :postal_code =>	"91901" },
    { :id => 2, :state =>	"CA", :county =>	"San Diego County", :city => "Bonita", :neighborhood => "", :postal_code =>	"91902" },
    { :id => 3, :state =>	"CA", :county =>	"San Diego County", :city => "Alpine", :neighborhood => "", :postal_code =>	"91903" },
    { :id => 4, :state =>	"CA", :county =>	"San Diego County", :city => "Boulevard", :neighborhood => "", :postal_code =>	"91905" },
    { :id => 5, :state =>	"CA", :county =>	"San Diego County", :city => "Campo", :neighborhood => "", :postal_code =>	"91906" },
    { :id => 6, :state =>	"CA", :county =>	"San Diego County", :city => "Bonita", :neighborhood => "", :postal_code =>	"91908" },
    { :id => 7, :state =>	"CA", :county =>	"San Diego County", :city => "Chula Vista", :neighborhood => "", :postal_code =>	"91909" },
    { :id => 8, :state =>	"CA", :county =>	"San Diego County", :city => "Chula Vista", :neighborhood => "", :postal_code =>	"91910" },
    { :id => 9, :state =>	"CA", :county =>	"San Diego County", :city => "Chula Vista", :neighborhood => "", :postal_code =>	"91911" },
    { :id => 10, :state =>	"CA", :county =>	"San Diego County", :city => "Chula Vista", :neighborhood => "", :postal_code =>	"91912" },
    { :id => 11, :state =>	"CA", :county =>	"San Diego County", :city => "Chula Vista", :neighborhood => "", :postal_code =>	"91913" },
    { :id => 12, :state =>	"CA", :county =>	"San Diego County", :city => "Chula Vista", :neighborhood => "", :postal_code =>	"91914" },
    { :id => 13, :state =>	"CA", :county =>	"San Diego County", :city => "Chula Vista", :neighborhood => "", :postal_code =>	"91915" },
    { :id => 14, :state =>	"CA", :county =>	"San Diego County", :city => "Descanso", :neighborhood => "", :postal_code =>	"91916" },
    { :id => 15, :state =>	"CA", :county =>	"San Diego County", :city => "Dulzura", :neighborhood => "", :postal_code =>	"91917" },
    { :id => 16, :state =>	"CA", :county =>	"San Diego County", :city => "Chula Vista", :neighborhood => "", :postal_code =>	"91921" },
    { :id => 17, :state =>	"CA", :county =>	"San Diego County", :city => "Guatay", :neighborhood => "", :postal_code =>	"91931" },
    { :id => 18, :state =>	"CA", :county =>	"San Diego County", :city => "Imperial Beach", :neighborhood => "", :postal_code =>	"91932" },
    { :id => 19, :state =>	"CA", :county =>	"San Diego County", :city => "Imperial Beach", :neighborhood => "", :postal_code =>	"91933" },
    { :id => 20, :state =>	"CA", :county =>	"San Diego County", :city => "Jacumba", :neighborhood => "", :postal_code =>	"91934" },
    { :id => 21, :state =>	"CA", :county =>	"San Diego County", :city => "Jamul", :neighborhood => "", :postal_code =>	"91935" },
    { :id => 22, :state =>	"CA", :county =>	"San Diego County", :city => "La Mesa", :neighborhood => "", :postal_code =>	"91941" },
    { :id => 23, :state =>	"CA", :county =>	"San Diego County", :city => "La Mesa", :neighborhood => "", :postal_code =>	"91942" },
    { :id => 24, :state =>	"CA", :county =>	"San Diego County", :city => "La Mesa", :neighborhood => "", :postal_code =>	"91943" },
    { :id => 25, :state =>	"CA", :county =>	"San Diego County", :city => "La Mesa", :neighborhood => "", :postal_code =>	"91944" },
    { :id => 26, :state =>	"CA", :county =>	"San Diego County", :city => "Lemon Grove", :neighborhood => "", :postal_code =>	"91945" },
    { :id => 27, :state =>	"CA", :county =>	"San Diego County", :city => "Lemon Grove", :neighborhood => "", :postal_code =>	"91946" },
    { :id => 28, :state =>	"CA", :county =>	"San Diego County", :city => "Lincoln Acres", :neighborhood => "", :postal_code =>	"91947" },
    { :id => 29, :state =>	"CA", :county =>	"San Diego County", :city => "Mount Laguna", :neighborhood => "", :postal_code =>	"91948" },
    { :id => 30, :state =>	"CA", :county =>	"San Diego County", :city => "National City", :neighborhood => "", :postal_code =>	"91950" },
    { :id => 31, :state =>	"CA", :county =>	"San Diego County", :city => "National City", :neighborhood => "", :postal_code =>	"91951" },
    { :id => 32, :state =>	"CA", :county =>	"San Diego County", :city => "Pine Valley", :neighborhood => "", :postal_code =>	"91962" },
    { :id => 33, :state =>	"CA", :county =>	"San Diego County", :city => "Potrero", :neighborhood => "", :postal_code =>	"91963" },
    { :id => 34, :state =>	"CA", :county =>	"San Diego County", :city => "Spring Valley", :neighborhood => "", :postal_code =>	"91976" },
    { :id => 35, :state =>	"CA", :county =>	"San Diego County", :city => "Spring Valley", :neighborhood => "", :postal_code =>	"91977" },
    { :id => 36, :state =>	"CA", :county =>	"San Diego County", :city => "Spring Valley", :neighborhood => "", :postal_code =>	"91978" },
    { :id => 37, :state =>	"CA", :county =>	"San Diego County", :city => "Spring Valley", :neighborhood => "", :postal_code =>	"91979" },
    { :id => 38, :state =>	"CA", :county =>	"San Diego County", :city => "Tecate", :neighborhood => "", :postal_code =>	"91980" },
    { :id => 39, :state =>	"CA", :county =>	"San Diego County", :city => "Bonsall", :neighborhood => "", :postal_code =>	"92003" },
    { :id => 40, :state =>	"CA", :county =>	"San Diego County", :city => "Borrego Springs", :neighborhood => "", :postal_code =>	"92004" },
    { :id => 41, :state =>	"CA", :county =>	"San Diego County", :city => "Cardiff", :neighborhood => "", :postal_code =>	"92007" },
    { :id => 42, :state =>	"CA", :county =>	"San Diego County", :city => "Carlsbad", :neighborhood => "", :postal_code =>	"92008" },
    { :id => 43, :state =>	"CA", :county =>	"San Diego County", :city => "Carlsbad", :neighborhood => "", :postal_code =>	"92009" },
    { :id => 44, :state =>	"CA", :county =>	"San Diego County", :city => "Carlsbad", :neighborhood => "", :postal_code =>	"92013" },
    { :id => 45, :state =>	"CA", :county =>	"San Diego County", :city => "Del Mar", :neighborhood => "", :postal_code =>	"92014" },
    { :id => 46, :state =>	"CA", :county =>	"San Diego County", :city => "Carlsbad", :neighborhood => "", :postal_code =>	"92018" },
    { :id => 47, :state =>	"CA", :county =>	"San Diego County", :city => "El Cajon", :neighborhood => "", :postal_code =>	"92019" },
    { :id => 48, :state =>	"CA", :county =>	"San Diego County", :city => "El Cajon", :neighborhood => "", :postal_code =>	"92020" },
    { :id => 49, :state =>	"CA", :county =>	"San Diego County", :city => "El Cajon", :neighborhood => "", :postal_code =>	"92021" },
    { :id => 50, :state =>	"CA", :county =>	"San Diego County", :city => "El Cajon", :neighborhood => "", :postal_code =>	"92022" },
    { :id => 51, :state =>	"CA", :county =>	"San Diego County", :city => "Encinitas", :neighborhood => "", :postal_code =>	"92023" },
    { :id => 52, :state =>	"CA", :county =>	"San Diego County", :city => "Encinitas", :neighborhood => "", :postal_code =>	"92024" },
    { :id => 53, :state =>	"CA", :county =>	"San Diego County", :city => "Escondido", :neighborhood => "", :postal_code =>	"92025" },
    { :id => 54, :state =>	"CA", :county =>	"San Diego County", :city => "Escondido", :neighborhood => "", :postal_code =>	"92026" },
    { :id => 55, :state =>	"CA", :county =>	"San Diego County", :city => "Escondido", :neighborhood => "", :postal_code =>	"92027" },
    { :id => 56, :state =>	"CA", :county =>	"San Diego County", :city => "Fallbrook", :neighborhood => "", :postal_code =>	"92028" },
    { :id => 57, :state =>	"CA", :county =>	"San Diego County", :city => "Escondido", :neighborhood => "", :postal_code =>	"92029" },
    { :id => 58, :state =>	"CA", :county =>	"San Diego County", :city => "Escondido", :neighborhood => "", :postal_code =>	"92030" },
    { :id => 59, :state =>	"CA", :county =>	"San Diego County", :city => "Escondido", :neighborhood => "", :postal_code =>	"92033" },
    { :id => 60, :state =>	"CA", :county =>	"San Diego County", :city => "Julian", :neighborhood => "", :postal_code =>	"92036" },
    { :id => 61, :state =>	"CA", :county =>	"San Diego County", :city => "La Jolla", :neighborhood => "", :postal_code =>	"92037" },
    { :id => 62, :state =>	"CA", :county =>	"San Diego County", :city => "La Jolla", :neighborhood => "", :postal_code =>	"92038" },
    { :id => 63, :state =>	"CA", :county =>	"San Diego County", :city => "La Jolla", :neighborhood => "", :postal_code =>	"92039" },
    { :id => 64, :state =>	"CA", :county =>	"San Diego County", :city => "Lakeside", :neighborhood => "", :postal_code =>	"92040" },
    { :id => 65, :state =>	"CA", :county =>	"San Diego County", :city => "Escondido", :neighborhood => "", :postal_code =>	"92046" },
    { :id => 66, :state =>	"CA", :county =>	"San Diego County", :city => "Oceanside", :neighborhood => "", :postal_code =>	"92049" },
    { :id => 67, :state =>	"CA", :county =>	"San Diego County", :city => "Oceanside", :neighborhood => "", :postal_code =>	"92051" },
    { :id => 68, :state =>	"CA", :county =>	"San Diego County", :city => "Oceanside", :neighborhood => "", :postal_code =>	"92052" },
    { :id => 69, :state =>	"CA", :county =>	"San Diego County", :city => "Camp Pendleton", :neighborhood => "", :postal_code =>	"92054" },
    { :id => 70, :state =>	"CA", :county =>	"San Diego County", :city => "Oceanside", :neighborhood => "", :postal_code =>	"92054" },
    { :id => 71, :state =>	"CA", :county =>	"San Diego County", :city => "Camp Pendleton", :neighborhood => "", :postal_code =>	"92055" },
    { :id => 72, :state =>	"CA", :county =>	"San Diego County", :city => "Oceanside", :neighborhood => "", :postal_code =>	"92055" },
    { :id => 73, :state =>	"CA", :county =>	"San Diego County", :city => "Oceanside", :neighborhood => "", :postal_code =>	"92056" },
    { :id => 74, :state =>	"CA", :county =>	"San Diego County", :city => "Oceanside", :neighborhood => "", :postal_code =>	"92057" },
    { :id => 75, :state =>	"CA", :county =>	"San Diego County", :city => "Oceanside", :neighborhood => "", :postal_code =>	"92058" },
    { :id => 76, :state =>	"CA", :county =>	"San Diego County", :city => "Pala", :neighborhood => "", :postal_code =>	"92059" },
    { :id => 77, :state =>	"CA", :county =>	"San Diego County", :city => "Palomar Mountain", :neighborhood => "", :postal_code =>	"92060" },
    { :id => 78, :state =>	"CA", :county =>	"San Diego County", :city => "Pala", :neighborhood => "", :postal_code =>	"92061" },
    { :id => 79, :state =>	"CA", :county =>	"San Diego County", :city => "Pauma Valley", :neighborhood => "", :postal_code =>	"92061" },
    { :id => 80, :state =>	"CA", :county =>	"San Diego County", :city => "Poway", :neighborhood => "", :postal_code =>	"92064" },
    { :id => 81, :state =>	"CA", :county =>	"San Diego County", :city => "Ramona", :neighborhood => "", :postal_code =>	"92065" },
    { :id => 82, :state =>	"CA", :county =>	"San Diego County", :city => "Ranchita", :neighborhood => "", :postal_code =>	"92066" },
    { :id => 83, :state =>	"CA", :county =>	"San Diego County", :city => "Warner Springs", :neighborhood => "", :postal_code =>	"92066" },
    { :id => 84, :state =>	"CA", :county =>	"San Diego County", :city => "Rancho Santa Fe", :neighborhood => "", :postal_code =>	"92067" },
    { :id => 85, :state =>	"CA", :county =>	"San Diego County", :city => "San Luis Rey", :neighborhood => "", :postal_code =>	"92068" },
    { :id => 86, :state =>	"CA", :county =>	"San Diego County", :city => "San Marcos", :neighborhood => "", :postal_code =>	"92069" },
    { :id => 87, :state =>	"CA", :county =>	"San Diego County", :city => "Santa Ysabel", :neighborhood => "", :postal_code =>	"92070" },
    { :id => 88, :state =>	"CA", :county =>	"San Diego County", :city => "Santee", :neighborhood => "", :postal_code =>	"92071" },
    { :id => 89, :state =>	"CA", :county =>	"San Diego County", :city => "Santee", :neighborhood => "", :postal_code =>	"92072" },
    { :id => 90, :state =>	"CA", :county =>	"San Diego County", :city => "Poway", :neighborhood => "", :postal_code =>	"92074" },
    { :id => 91, :state =>	"CA", :county =>	"San Diego County", :city => "Solana Beach", :neighborhood => "", :postal_code =>	"92075" },
    { :id => 92, :state =>	"CA", :county =>	"San Diego County", :city => "San Marcos", :neighborhood => "", :postal_code =>	"92078" },
    { :id => 93, :state =>	"CA", :county =>	"San Diego County", :city => "San Marcos", :neighborhood => "", :postal_code =>	"92079" },
    { :id => 94, :state =>	"CA", :county =>	"San Diego County", :city => "Valley Center", :neighborhood => "", :postal_code =>	"92082" },
    { :id => 95, :state =>	"CA", :county =>	"San Diego County", :city => "Vista", :neighborhood => "", :postal_code =>	"92083" },
    { :id => 96, :state =>	"CA", :county =>	"San Diego County", :city => "Vista", :neighborhood => "", :postal_code =>	"92084" },
    { :id => 97, :state =>	"CA", :county =>	"San Diego County", :city => "Vista", :neighborhood => "", :postal_code =>	"92085" },
    { :id => 98, :state =>	"CA", :county =>	"San Diego County", :city => "Warner Springs", :neighborhood => "", :postal_code =>	"92086" },
    { :id => 99, :state =>	"CA", :county =>	"San Diego County", :city => "Fallbrook", :neighborhood => "", :postal_code =>	"92088" },
    { :id => 100, :state =>	"CA", :county =>	"San Diego County", :city => "Rancho Santa Fe", :neighborhood => "", :postal_code =>	"92091" },
    { :id => 101, :state =>	"CA", :county =>	"San Diego County", :city => "La Jolla", :neighborhood => "", :postal_code =>	"92092" },
    { :id => 102, :state =>	"CA", :county =>	"San Diego County", :city => "La Jolla", :neighborhood => "", :postal_code =>	"92093" },
    { :id => 103, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92101" },
    { :id => 104, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92102" },
    { :id => 105, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92103" },
    { :id => 106, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92104" },
    { :id => 107, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92105" },
    { :id => 108, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92106" },
    { :id => 109, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92107" },
    { :id => 110, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92108" },
    { :id => 111, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92109" },
    { :id => 112, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92110" },
    { :id => 113, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92111" },
    { :id => 114, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92112" },
    { :id => 115, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92113" },
    { :id => 116, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92114" },
    { :id => 117, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92115" },
    { :id => 118, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92116" },
    { :id => 119, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92117" },
    { :id => 120, :state =>	"CA", :county =>	"San Diego County", :city => "Coronado", :neighborhood => "", :postal_code =>	"92118" },
    { :id => 121, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92118" },
    { :id => 122, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92119" },
    { :id => 123, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92120" },
    { :id => 124, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92121" },
    { :id => 125, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92122" },
    { :id => 126, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92123" },
    { :id => 127, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92124" },
    { :id => 128, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92126" },
    { :id => 129, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92127" },
    { :id => 130, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92128" },
    { :id => 131, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92129" },
    { :id => 132, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92130" },
    { :id => 133, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92131" },
    { :id => 134, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92132" },
    { :id => 135, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92133" },
    { :id => 136, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92134" },
    { :id => 137, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92135" },
    { :id => 138, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92136" },
    { :id => 139, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92137" },
    { :id => 140, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92138" },
    { :id => 141, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92139" },
    { :id => 142, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92140" },
    { :id => 143, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92142" },
    { :id => 144, :state =>	"CA", :county =>	"San Diego County", :city => "San Ysidro", :neighborhood => "", :postal_code =>	"92143" },
    { :id => 145, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92143" },
    { :id => 146, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92145" },
    { :id => 147, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92147" },
    { :id => 148, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92149" },
    { :id => 149, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92150" },
    { :id => 150, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92152" },
    { :id => 151, :state =>	"CA", :county =>	"San Diego County", :city => "Nestor", :neighborhood => "", :postal_code =>	"92153" },
    { :id => 152, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92153" },
    { :id => 153, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92154" },
    { :id => 154, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92155" },
    { :id => 155, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92159" },
    { :id => 156, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92160" },
    { :id => 157, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92162" },
    { :id => 158, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92163" },
    { :id => 159, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92164" },
    { :id => 160, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92165" },
    { :id => 161, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92166" },
    { :id => 162, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92167" },
    { :id => 163, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92168" },
    { :id => 164, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92169" },
    { :id => 165, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92170" },
    { :id => 166, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92171" },
    { :id => 167, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92172" },
    { :id => 168, :state =>	"CA", :county =>	"San Diego County", :city => "San Ysidro", :neighborhood => "", :postal_code =>	"92173" },
    { :id => 169, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92173" },
    { :id => 170, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92174" },
    { :id => 171, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92175" },
    { :id => 172, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92176" },
    { :id => 173, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92177" },
    { :id => 174, :state =>	"CA", :county =>	"San Diego County", :city => "Coronado", :neighborhood => "", :postal_code =>	"92178" },
    { :id => 175, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92178" },
    { :id => 176, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92182" },
    { :id => 177, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92186" },
    { :id => 178, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92190" },
    { :id => 179, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92191" },
    { :id => 180, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92192" },
    { :id => 181, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92193" },
    { :id => 182, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92194" },
    { :id => 183, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92195" },
    { :id => 184, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92196" },
    { :id => 185, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92197" },
    { :id => 186, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92198" },
    { :id => 187, :state =>	"CA", :county =>	"San Diego County", :city => "San Diego", :neighborhood => "", :postal_code =>	"92199" }
  ]
end